// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awposejbigiqwtewizwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3cG9zZWpiaWdpcXd0ZXdpendvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTY2NjksImV4cCI6MjA3Mzc3MjY2OX0.2319LAHJ7NIXRs0LkzsCfL0oNu0h-6wJcNXPGmMbTyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});